### ISSUE TITLE
horizontal?

### ISSUE THREAD

**Issue by jlprado** [Max-Makhrov/sheets2pdf_gs#1]
https://github.com/Max-Makhrov/sheets2pdf_gs/blob/25babc086a414c86c87aa5083a1bdf953ad5ec35/Code.gs#L602

**Comment by Max-Makhrov** [comment]
Hi @[**jlprado**](https://github.com/jlprado)**!**

what is wrong with line 602?

How should I fix that?

**Comment by jlprado** [comment]
the name of the property is currently: "hirizontal" (with an i as the second letter), maybe it was a typo? and the word should be horizontal (with an o as the second letter)? thanks,

**Comment by Max-Makhrov** [comment]
Fixed

https://github.com/Max-Makhrov/sheets2pdf_gs/blob/6c8fc9f68f07597ee3b46a7d869fb2f8a9d55f3e/Code.gs#L602

Thank you very much!
